Update application_test.yml

diff --git a/.github/workflows/application_test.yml b/.github/workflows/application_test.yml
--- a/.github/workflows/application_test.yml
+++ b/.github/workflows/application_test.yml
@@ -82,3 +82,27 @@ jobs:
         run: |
           cd App_Test
           pytest
+
+      - name: Install Packer
+        run: |
+          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
+          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
+          sudo apt-get update && sudo apt-get install packer
+
+      - name: Run Packer fmt
+        run: |
+          sudo cd App_Test
+          packer fmt -check .
+        continue-on-error: true
+        id: packer_fmt
+
+      - name: Check Packer fmt result
+        if: steps.packer_fmt.outcome == 'failure'
+        run: |
+          echo "Packer fmt check failed. Please format your Packer templates."
+          exit 1
+
+      - name: Run Packer validate
+        run: |
+          packer validate .
+        id: packer_validate
